### PR TITLE
change notification color + edit manual install guide

### PR DESCRIPTION
**Pull request by whois-hoeless**
My bad I forgot to change the notification color of my color scheme, I changed it so it should be good now. 
I also edited your Readme a little bit, I believe that you need to extract the folder and all that so I added that in the instructions, I hope that's fine :>
Lastly, do you need preview images of the theme? If so I can make some for you too

### CODE REVIEW

**Comment by ohitstom** [comment]
please append a preview image to the table of of ones with have under comfy/readme.md

other than that can you remove the part about deleting the folder when you are done from the install since that's out of scope

**Comment by whois-hoeless** [comment]
Alright, I reverted the part with deleting the folder and I appended a preview image to the table. I hope the link name doesn't really matter too much, because I cannot make a `comfy-themes.github.io` link, I just took the raw image link of my repo, but you can change that if you want. Also if there's an issue with the image (if you want it to look differently or something like that) then just leave me another comment and I can change that too :)

**Comment by ohitstom** [comment]
you need to place an image file in the previews folder and add a GitHub io link pointing to it, obviously this link won't 'exist' until the pr is merged

**Comment by ohitstom** [comment]
I'll merge for now and fix it after

**Comment by whois-hoeless** [comment]
oh alright I didn't know that, thanks for informing me :)

**Pull request merged**
