### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by NotMephisto**
Fix link

### CODE REVIEW

**Comment by ohitstom** [comment]
I'm a bit confused by this PR, mind explaining im just curious your thoughts xd

**Comment by NotMephisto** [comment]
> I'm a bit confused by this PR, mind explaining im just curious your thoughts xd

I'm puzzled too, I thought I was editing my fork. I apologize for the inconvenience :c

**Comment by ohitstom** [comment]
> > I'm a bit confused by this PR, mind explaining im just curious your thoughts xd
> 
> I'm puzzled too, I thought I was editing my fork. I apologize for the inconvenience :c

haha no worries :)

**Comment by ohitstom** [comment]
> > I'm a bit confused by this PR, mind explaining im just curious your thoughts xd
> 
> I'm puzzled too, I thought I was editing my fork. I apologize for the inconvenience :c

What's your custom scheme look like? if it's good I'll happily add it

**Comment by NotMephisto** [comment]
> > > I'm a bit confused by this PR, mind explaining im just curious your thoughts xd
> > 
> > 
> > I'm puzzled too, I thought I was editing my fork. I apologize for the inconvenience :c
> 
> What's your custom scheme look like? if it's good I'll happily add it

It changes dynamically to match the wallpaper, I'm just starting to figure out how your theme is organized and implement this

**Comment by ohitstom** [comment]
sounds very cool, hope all goes to plan!

**Comment by NotMephisto** [comment]
Is there any way I can get in touch later to ask questions?

**Comment by ohitstom** [comment]
> Is there any way I can get in touch later to ask questions?

@ohitstom on discord would be easiest for me!

**Pull request closed without merging**
