### PR TITLE
feat(extension): automatic update

### PR DESCRIPTION
**Pull request by kyrie25**
Automatically updates the extension script by appending script fetched from GitHub

<details>
<summary>Proof the update is working <i>(fetched script & dynamic background image)</i></summary>

image

</details>

<details>
<summary>Testing script used:</summary>

```js
const script = document.createElement("SCRIPT");
script.setAttribute("type", "text/javascript");
script.setAttribute(
  "src",
  "https://comfy-themes.github.io/Spicetify/Comfy/Comfy.js"
);
document.head.appendChild(script);
```

</details>

Note:
- For the script edit: Unused variable is commented out for easier maintaining:
image

<details>
<summary>It has been tested to be working with the change but I will undo it if the variable is said to be useful</summary>

image

</details>

- For the readme changes: Aren't you supposed to copy CSS file content into `user.css` instead of the extension `js` file?
image

### CODE REVIEW

**Comment by ohitstom** [comment]
I believe that the lyricsbackground variable is indeed used in the css so once you've reverted the removal this seems like a great thing to merge.

**Comment by kyrie25** [comment]
> I believe that the lyricsbackground variable is indeed used in the css, once you've reverted the removal this seems like a great feature to merge!
> 
> You may want to update your branch to the latest commits first aswell!

Done and done.

**Comment by ohitstom** [comment]
Awesome thanks for supporting comfy ❣️

**Comment by kyrie25** [comment]
Glad to be of service!

**Pull request merged**
