### PR TITLE
fix: several changes

### PR DESCRIPTION
**Pull request by kyrie25**
- Fix album image width reducing on long playlist/album name

<details>
<summary>Details</summary>

- Before
image

- After
image

</details>

- Remove padding rule for Lyrics Plus to apply default value

<details>
<summary>Details</summary>

- Before
image

- After
image

</details>

### CODE REVIEW

**Comment by ohitstom** [comment]
Will test these commits when I get in, is this for the supported versions or latest? Latest support would to in dev branch if so :)

**Comment by kyrie25** [comment]
> Will test these commits when I get in, is this for the supported versions or latest? Latest support would go in dev branch if so :)

Latest yeah, but these are just ruleset changes for the existing selectors so I'm pretty sure they're not version dependent. But it's your call.

**Comment by ohitstom** [comment]
> Latest yeah, but these are just ruleset changes for the existing selectors so I'm pretty sure they're not version dependent. But it's your call.

All good will test it when I get in, it it's existing selectors I doubt it will be an issue but the issues you showcased I've not had on supported versions...

**Comment by ohitstom** [comment]
Yup its just as i thought, the lyrics plus padding is just because of your latest version, however i think the overflowing text is fine to push, or you can make a pull request for the dev branch for both if you'd like?

**Pull request merged**
